### ISSUE TITLE
Can't build, needs addons-ecs.forgesvc.net which I guess doesn't exist anymore?

### ISSUE THREAD

**Issue by bhechinger** [henkelmax/curseforge-modpack-server-generator#1]
```
Failed to build server files: request to https://addons-ecs.forgesvc.net/api/v2/addon/581495/ failed, reason: getaddrinfo ENOTFOUND addons-ecs.forgesvc.net
```

Trying to look that up gets nothing:
```
➜ host addons-ecs.forgesvc.net 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases: 

Host addons-ecs.forgesvc.net not found: 3(NXDOMAIN)
```

**Comment by MWG-Logan** [comment]
Running into this as well.
This seems to be the only non-functional part of my workflow now

```
Building Server
  Using temp directory '/tmp/79e990e7-[8](https://github.com/MW-GC/MC-Critical_Mass-1.16/actions/runs/3955077435/jobs/6773039410#step:4:9)ab1-46b0-[9](https://github.com/MW-GC/MC-Critical_Mass-1.16/actions/runs/3955077435/jobs/6773039410#step:4:10)c7b-8a3d44da5ca5'
  Parsing modpack zip file './modpack.zip'
  Reading manifest.json
  Unpacking modpack zip to '/tmp/9c578c9d-fc5a-4c93-98e4-862fcab4aa86'
  Unpacked modpack zip to '/tmp/9c578c9d-fc5a-4c93-98e4-862fcab4aa86'
  Copying overrides '/tmp/9c578c9d-fc5a-4c93-98e4-862fcab4aa86/overrides' to '/tmp/79e990e7-8ab1-46b0-9c7b-8a3d44da5ca5'
  Copied overrides
  Deleting '/tmp/9c578c9d-fc5a-4c93-98e4-862fcab4aa86'
  Deleted '/tmp/9c578c9d-fc5a-4c93-98e4-862fcab4aa86'
  Generating scripts
  Generating forge downloading scripts
  Adding mod downloads
  Fetching information of '260262'
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-[10](https://github.com/MW-GC/MC-Critical_Mass-1.16/actions/runs/3955077435/jobs/6773039410#step:4:11)-[11](https://github.com/MW-GC/MC-Critical_Mass-1.16/actions/runs/3955077435/jobs/6773039410#step:4:12)-github-actions-deprecating-save-state-and-set-output-commands/
(node:1699) UnhandledPromiseRejectionWarning: FetchError: request to https://addons-ecs.forgesvc.net/api/v2/addon/260262/ failed, reason: getaddrinfo ENOTFOUND addons-ecs.forgesvc.net
    at ClientRequest.<anonymous> (/home/runner/work/_actions/henkelmax/build-modpack-server-action/v1.0.0/dist/index.js:29952:11)
    at ClientRequest.emit (events.js:3[14](https://github.com/MW-GC/MC-Critical_Mass-1.16/actions/runs/3955077435/jobs/6773039410#step:4:15):20)
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:[16](https://github.com/MW-GC/MC-Critical_Mass-1.16/actions/runs/3955077435/jobs/6773039410#step:4:17)99) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1699) [DEP00[18](https://github.com/MW-GC/MC-Critical_Mass-1.16/actions/runs/3955077435/jobs/6773039410#step:4:19)] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
